#!/usr/bin/env bash
# m4c-link.sh — produce a LINKED amdgpu bring-up object (the M4c milestone).
#
# Builds on m4-link.sh: it compiles the real Phoenix-path amdgpu .c subset and the
# raeen_linuxkpi staticlib (LinuxKPI seam = 0). This script then:
#   (1) auto-generates a stub for every remaining external symbol — the off-path
#       buckets we deliberately don't compile yet (other-ASIC reg_base, off-path
#       IP blocks, ttm_/drm_sched_/drm-core component source). Function-like names
#       become `void s(void){}`; data-like (*_ip_block/_funcs/_ops) become a zeroed
#       buffer (their address resolves; Phoenix never adds them to its init list).
#   (2) relocatable-links the real objects + stubs into one object, and
#   (3) confirms ZERO unresolved symbols once the raeen_linuxkpi staticlib is in —
#       i.e. the real amdgpu bring-up graph LINKS end to end.
#
# This is the "produce a linked binary" milestone: real init code for the Phoenix
# MES path, stubs only for the deliberately-deferred off-path code. Replacing a
# stub with its real .c is the convergence toward a functional M5 init.
set -uo pipefail

# Derived from this script's location so the build runs on any host (was a hardcoded
# /mnt/c/... WSL path that broke every native-Linux box).
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OBJ=$HOME/m4-obj
TGT=${CARGO_TARGET_DIR:-$HOME/m4-target}
# FREESTANDING=1 -> the staticlib m4-link.sh builds is the bare-metal (-none) one;
# use the SAME triple here or libdef.txt comes up empty and we wrongly stub every
# symbol raeen_linuxkpi actually defines (-> duplicate symbols at the daemon link).
[ -n "${FREESTANDING:-}" ] && RTARGET=x86_64-unknown-none || RTARGET=x86_64-unknown-linux-gnu
LIB=$TGT/$RTARGET/release/libraeen_linuxkpi.a

green() { printf '\033[32m%s\033[0m\n' "$*"; }

# (0) compile the real objects + staticlib (m4-link.sh leaves them in $OBJ).
bash "$REPO/linuxkpi-drm/m4-link.sh" >/tmp/m4-link.log 2>&1 || {
  cat /tmp/m4-link.log >&2
  exit 1
}
[ -d "$OBJ" ] || { echo "[m4c] $OBJ missing — m4-link.sh failed, see /tmp/m4-link.log"; exit 1; }

cd "$OBJ"
# Remove any prior merged output + stub object BEFORE scanning defined/undefined
# symbols. If the stale amdgpu-bringup.o (which carries ALL the weak stubs) is in
# the `nm *.o` scan, its stubs count as "provided" so almost nothing gets
# re-stubbed — then the fresh ld -r (which excludes amdgpu-bringup.o) drops those
# stubs and the daemon link fails with hundreds of undefined symbols.
rm -f amdgpu-bringup.o stubs.o
nm *.o            2>/dev/null | awk 'NF==3 && $2!="U" {print $3}' | sort -u > objdef.txt
nm -u *.o         2>/dev/null | awk '{print $2}'               | sort -u > undef.txt
nm "$LIB"         2>/dev/null | awk 'NF==3 && $2!="U" {print $3}' | sort -u > libdef.txt
cat objdef.txt libdef.txt | sort -u > provided.txt
comm -23 undef.txt provided.txt | grep -vE '^$' > tostub.txt
echo "[m4c] real objects: $(ls *.o | grep -v stubs | wc -l)   external symbols to stub: $(wc -l < tostub.txt)"

# (1) generate the off-path stub TU. Every stub is WEAK so that any symbol the
# real raeen_linuxkpi (rlib) provides overrides the inert stub at the daemon link
# instead of colliding as a duplicate — the rlib and the staticlib symbol sets can
# differ, so subtracting libdef alone is not enough. Weak = real impl always wins,
# off-path symbols nothing provides fall back to the inert stub.
{
  echo '/* AUTO-GENERATED by m4c-link.sh — off-path bring-up stubs (MPL, original). */'
  echo '/* WEAK: real raeen_linuxkpi definitions override these; unprovided -> inert. */'
  while read -r s; do
    case "$s" in
      __stack_chk_fail|_GLOBAL_OFFSET_TABLE_) : ;;            # CRT / linker-provided
      # amdgpu naming: `X_set_Y_funcs` / `set_X` are FUNCTIONS that ASSIGN pointer
      # tables — NOT data. Data-stubbing them (below) makes a real call jump into a
      # zeroed buffer -> instruction-fetch fault (e.g. yellow_carp_set_ppt_funcs on
      # the Phoenix SMU path). Emit them as empty functions FIRST.
      set_*|*_set_*) echo "__attribute__((weak)) void $s(void) {}" ;;
      *_ip_block|*_funcs|*_ops|*_caps|*_funcs_*) echo "__attribute__((weak)) char $s[8192] = {0};" ;;
      *) echo "__attribute__((weak)) void $s(void) {}" ;;
    esac
  done < tostub.txt
} > stubs.c
# match the object build's mode (FREESTANDING=1 -> bare-metal stubs too).
[ -n "${FREESTANDING:-}" ] && STUB_CFLAGS="-ffreestanding -mno-red-zone" || STUB_CFLAGS=""
gcc -std=gnu11 -fno-stack-protector $STUB_CFLAGS -c stubs.c -o stubs.o 2>/tmp/m4c-stubs.log || {
  echo "[m4c] stubs.c failed to compile — see /tmp/m4c-stubs.log"; exit 1; }

# (2) relocatable-link the real objects + stubs. Remove a prior merged output
# first and exclude it from the input glob, or `ld -r` errors "input file
# amdgpu-bringup.o is the same as output file" when a stale one is present.
rm -f amdgpu-bringup.o
ld -r $(ls *.o | grep -vE '^(stubs|amdgpu-bringup)\.o$') stubs.o -o amdgpu-bringup.o 2>/tmp/m4c-ld.log || {
  echo "[m4c] ld -r failed — see /tmp/m4c-ld.log"; exit 1; }

# (3) what remains undefined after the merge, and after the staticlib resolves it.
nm -u amdgpu-bringup.o 2>/dev/null | awk '{print $2}' | sort -u > stillundef.txt
comm -23 stillundef.txt libdef.txt | grep -vE '^$' > final-unresolved.txt
sz=$(stat -c%s amdgpu-bringup.o 2>/dev/null || echo '?')

echo "[m4c] merged object amdgpu-bringup.o = ${sz} bytes"
echo "[m4c] undefined after objects+stubs: $(wc -l < stillundef.txt); after raeen_linuxkpi staticlib: $(wc -l < final-unresolved.txt)"

# (5) M5 readiness: split the stubs into ON-PATH (a real Phoenix amdgpu_device_init
# dereferences/executes these — they MUST become real .c before an M5 run is
# meaningful) vs OFF-PATH (other ASIC / SR-IOV / KFD / userq / display / video —
# safe to leave stubbed). See M5-ONPATH-AUDIT.md for the rationale.
ONPATH='^(ttm_|drm_sched|amdgpu_dpm|smu_cmn|smu_v13|amdgpu_smu|smu_set|smu_get|smu_late|smu_feature|smu_init|smu_hw|smu_sw|ih_v6_1|vcn_v4_0|jpeg_v4_0|umsch_mm_v4_0|pp_smu_ip)'
# Prefix-match false positives that are NOT on the *Phoenix* init path (verified):
#  - other-ASIC IP variants: *_v4_0_3/_5 (Phoenix adds the base v4_0), pp_smu (uses
#    swsmu not powerplay), non-13.0.4 smu13 variants (0/5/6/7/10/12 — Phoenix=13.0.4).
#  - ttm_backup (swap) + ttm_bo_vm (userspace mmap fault) — not reached during the
#    headless MES/GFX init (no reclaim, no userspace mmap).
SAFE='(_v4_0_[0-9]|smu_v13_0_(0|5|6|7|10|12)|pp_smu|ttm_backup|ttm_bo_vm)'
grep -E "$ONPATH" tostub.txt | grep -vE "$SAFE" > onpath-stubs.txt  || true
{ grep -vE "$ONPATH" tostub.txt; grep -E "$ONPATH" tostub.txt | grep -E "$SAFE"; } | sort -u > offpath-stubs.txt || true
echo "[m4c] M5-readiness — stubs ON the Phoenix init path (must become real): $(wc -l < onpath-stubs.txt); OFF-path (safe stub): $(wc -l < offpath-stubs.txt)"
if [ "$(wc -l < final-unresolved.txt)" -eq 0 ]; then
  green "[m4c] LINKED: the amdgpu bring-up object graph resolves fully against raeen_linuxkpi."
else
  echo "[m4c] still unresolved (not in staticlib):"; cat final-unresolved.txt
fi
