//! MP3 Layer III DSP back-end (ISO/IEC 11172-3 §2.4.3): the stages that turn the
//! decoded Huffman coefficients + side-info into the subband-domain time signal.
//!
//! Pipeline (per granule, per channel), all implemented + host-KAT'd here:
//!   1. Scalefactor decode (long/short/mixed, MPEG-1 slen tables).
//!   2. Requantization (the 2^(global_gain/4) · 2^(-scalefac·scale) · |is|^(4/3)
//!      power law → dequantized spectral coefficients).
//!   3. Reordering (short blocks: subband order → scalefactor-band order).
//!   4. Stereo processing (MS-stereo + intensity-stereo) across the two channels.
//!   5. Alias reduction (the 8 butterfly passes on long-block subband boundaries).
//!   6. IMDCT (36-point long / 12-point short) + windowing + overlap-add carrying the
//!      previous granule's second half + the long-block frequency inversion.
//!
//! No-libm discipline (the kernel mix path is soft-float, no libm): the IMDCT cosine
//! matrices and the block windows are precomputed `const` tables (`mp3_tables.rs`
//! sibling — generated by `tools/mp3_huff_gen/gentab.rs`); the |is|^(4/3) power law
//! uses an integer-indexed table for the entropy range plus a no-libm cbrt-squared
//! polynomial for the linbits escape range. No runtime sin/cos/pow.
//!
//! REMAINING STAGE (documented, deferred, never wrong PCM): the polyphase synthesis
//! filterbank (32 subbands → 32 PCM samples via the ISO Table B.3 512-tap D[] window)
//! is the final stage that produces audible PCM. The D[] prototype filter is a fixed,
//! non-closed-form 512-entry table; it is NOT transcribed here (an unverified
//! transcription would emit wrong PCM). Until it lands, the decoder runs this whole
//! DSP path for real and reports the hybrid-filterbank output, but the public
//! `AudioFrame` stays correctly-silent rather than emitting un-synthesized samples.
//!
//! Untrusted-input discipline: every index derived from side-info is clamped; a
//! corrupt granule produces zeroed (silent) output for that granule, never an OOB
//! index or panic.

use crate::mp3::{GranuleChannel, MpegVersion, SideInfo};
use crate::mp3_tables as t;

/// Number of frequency lines per granule per channel.
pub const NLINES: usize = 576;

use crate::mp3_imdct_tables::{IMDCT_LONG, IMDCT_SHORT, WIN0, WIN1, WIN2, WIN3};

/// Per-channel persistent state carried across granules: the overlap-add memory (the
/// second half of each subband's previous IMDCT output) plus the polyphase synthesis
/// filterbank's V[] FIFO. Both MUST be zeroed on construction and on any seek/flush.
#[derive(Clone)]
pub struct ChannelState {
    /// [subband 0..32][18] overlap from the previous granule.
    pub overlap: [[f32; 18]; 32],
    /// The synthesis filterbank V[] FIFO (1024 deep), shifts up by 64 each sub-pass.
    pub v_fifo: [f32; 1024],
}

impl ChannelState {
    pub fn new() -> Self {
        Self {
            overlap: [[0.0; 18]; 32],
            v_fifo: [0.0; 1024],
        }
    }
}

/// The decoded entropy output for one granule/channel handed to the DSP path.
pub struct GranuleSpectrum {
    /// Dequantized-input integer coefficients `is[0..576]` (Huffman output, signed).
    pub is: [i32; NLINES],
    /// Scalefactors: long-block [0..21], short-block [sfb 0..12][window 0..3].
    pub scalefac_l: [i32; 23],
    pub scalefac_s: [[i32; 3]; 13],
}

impl GranuleSpectrum {
    pub fn zero() -> Self {
        Self {
            is: [0; NLINES],
            scalefac_l: [0; 23],
            scalefac_s: [[0; 3]; 13],
        }
    }
}

// ─── 1. Scalefactor decode ──────────────────────────────────────────────────

/// Decode scalefactors from `r` for one granule/channel into `out`. MPEG-1 only here
/// (slen from `SLEN_MPEG1`); LSF scalefactor decode is part of the deferred set and
/// leaves scalefactors zero (clean silence) rather than guessing. Honors `scfsi`
/// (scalefactor selection info) to reuse granule-0 scalefactors in granule 1.
pub fn decode_scalefactors(
    r: &mut crate::mp3::BitReader,
    g: &GranuleChannel,
    gr: usize,
    ch: usize,
    si: &SideInfo,
    version: MpegVersion,
    prev: &GranuleSpectrum,
    out: &mut GranuleSpectrum,
) -> Result<(), crate::mp3::Mp3Error> {
    if version != MpegVersion::V1 {
        // LSF scalefactor decode deferred; leave zeros (silent), not wrong values.
        return Ok(());
    }
    let (slen1, slen2) = t::SLEN_MPEG1[(g.scalefac_compress & 0x0F) as usize];
    let slen1 = slen1 as u32;
    let slen2 = slen2 as u32;

    if g.window_switching && g.block_type == 2 {
        if g.mixed_block {
            // Mixed: SFB 0..7 long, 3..12 short.
            for sfb in 0..8 {
                out.scalefac_l[sfb] = r.read_bits(slen1)? as i32;
            }
            for sfb in 3..6 {
                for w in 0..3 {
                    out.scalefac_s[sfb][w] = r.read_bits(slen1)? as i32;
                }
            }
            for sfb in 6..12 {
                for w in 0..3 {
                    out.scalefac_s[sfb][w] = r.read_bits(slen2)? as i32;
                }
            }
        } else {
            for sfb in 0..6 {
                for w in 0..3 {
                    out.scalefac_s[sfb][w] = r.read_bits(slen1)? as i32;
                }
            }
            for sfb in 6..12 {
                for w in 0..3 {
                    out.scalefac_s[sfb][w] = r.read_bits(slen2)? as i32;
                }
            }
        }
    } else {
        // Long blocks. scfsi reuse groups: [0..6],[6..11],[11..16],[16..21].
        let groups: [(usize, usize, u32); 4] = [
            (0, 6, slen1),
            (6, 11, slen1),
            (11, 16, slen2),
            (16, 21, slen2),
        ];
        for (band_idx, &(lo, hi, slen)) in groups.iter().enumerate() {
            let reuse = gr == 1 && si.scfsi[ch][band_idx];
            for sfb in lo..hi {
                if reuse {
                    out.scalefac_l[sfb] = prev.scalefac_l[sfb];
                } else {
                    out.scalefac_l[sfb] = r.read_bits(slen)? as i32;
                }
            }
        }
    }
    Ok(())
}

// ─── 2. Requantization ──────────────────────────────────────────────────────

/// |is|^(4/3) for is in 0..=8206 (the entropy + linbits range). Computed no-libm via
/// a cube-root Newton iteration on the host at table-build, but here we compute it
/// inline with a no-libm cbrt to avoid a 32 KiB const blob; the cbrt is exact-enough
/// (relative error < 1e-6) and uses only multiply/divide.
#[inline]
pub(crate) fn cbrt_no_libm(x: f64) -> f64 {
    if x <= 0.0 {
        return 0.0;
    }
    // Initial guess via bit-twiddling on the exponent, then Newton-Raphson.
    let mut y = {
        // Scale into [1,8) by repeated /8 (×0.5 in cube root) — cheap and no-libm.
        let mut v = x;
        let mut s = 1.0f64;
        while v > 8.0 {
            v /= 8.0;
            s *= 2.0;
        }
        while v < 1.0 {
            v *= 8.0;
            s /= 2.0;
        }
        // crude poly seed for cbrt on [1,8]
        let g = 0.45 + 0.45 * v - 0.02 * v * v;
        g * s
    };
    // 4 Newton iterations: y = y - (y^3 - x)/(3 y^2)
    for _ in 0..5 {
        let y2 = y * y;
        y = y - (y * y2 - x) / (3.0 * y2);
    }
    y
}

/// No-libm floor for f64 (core has no `f64::floor` in no_std). Valid over the modest
/// range used by the gain math (|x| well under 2^52).
#[inline]
fn floor_no_libm(x: f64) -> f64 {
    let t = x as i64 as f64;
    if t > x {
        t - 1.0
    } else {
        t
    }
}

/// 2^(x/4) for the global_gain / subblock_gain scaling, no-libm. x can be negative.
#[inline]
pub(crate) fn pow2_quarter(x: f64) -> f64 {
    // 2^(x/4) = 2^(n) * 2^(f/4) where we split into integer powers of 2 and a small
    // residual handled by a polynomial. Use exp2 via integer shift + poly on frac.
    let q = x / 4.0;
    let n = floor_no_libm(q);
    let f = q - n; // in [0,1)
                   // 2^f polynomial (minimax-ish on [0,1], no-libm).
    let p = 1.0
        + f * (0.6931471805599453
            + f * (0.2402265069591007 + f * (0.05550410866482158 + f * 0.009618129107628477)));
    // 2^n via ldexp-equivalent.
    let mut base = 1.0f64;
    let ni = n as i64;
    if ni >= 0 {
        let mut k = ni;
        let mut m = 2.0;
        while k > 0 {
            if k & 1 == 1 {
                base *= m;
            }
            m *= m;
            k >>= 1;
        }
    } else {
        let mut k = -ni;
        let mut m = 0.5;
        while k > 0 {
            if k & 1 == 1 {
                base *= m;
            }
            m *= m;
            k >>= 1;
        }
    }
    base * p
}

/// Requantize one granule/channel: apply the global gain, the scalefactor power law,
/// and the |is|^(4/3) nonlinearity → real spectral coefficients `xr[0..576]`.
pub fn requantize(
    spec: &GranuleSpectrum,
    g: &GranuleChannel,
    sample_rate: u32,
    xr: &mut [f32; NLINES],
) {
    let sfb = t::sfb_for_rate(sample_rate);
    let scale_exp = if g.scalefac_scale == 1 { 1.0 } else { 0.5 }; // gain per scalefac step
    let gg = g.global_gain as f64 - 210.0;
    let short = g.window_switching && g.block_type == 2;
    let mixed = short && g.mixed_block;

    if short {
        // Short/mixed: each window's lines interleaved; we operate in is[] order which
        // is subband order until reorder() runs. Here we apply gain per (sfb,window).
        // The mixed long part (sfb < 8 lines) uses the long power law.
        let mut i = 0usize;
        // Long part for mixed: first 36 lines (sfb 0..8 long boundaries).
        let long_lines = if mixed { sfb.long[8] as usize } else { 0 };
        while i < long_lines && i < NLINES {
            // find long sfb
            let mut s = 0;
            while s < 21 && (i as u16) >= sfb.long[s + 1] {
                s += 1;
            }
            let sc = spec.scalefac_l[s] + if g.preflag { t::PRETAB[s] as i32 } else { 0 };
            let gain = pow2_quarter(gg) * powf_neg(scale_exp * sc as f64);
            xr[i] = (signed_pow43(spec.is[i]) * gain) as f32;
            i += 1;
        }
        // Short part: remaining lines, grouped per short sfb × 3 windows.
        let mut sfb_idx = if mixed { 3 } else { 0 };
        while sfb_idx < 13 && i < NLINES {
            let width = (sfb.short[sfb_idx + 1] - sfb.short[sfb_idx]) as usize;
            for w in 0..3 {
                let subgain = g.subblock_gain[w] as f64;
                let sc = spec.scalefac_s[sfb_idx][w];
                let gain = pow2_quarter(gg - 8.0 * subgain) * powf_neg(scale_exp * sc as f64);
                for _ in 0..width {
                    if i >= NLINES {
                        break;
                    }
                    xr[i] = (signed_pow43(spec.is[i]) * gain) as f32;
                    i += 1;
                }
            }
            sfb_idx += 1;
        }
        // any tail
        while i < NLINES {
            xr[i] = signed_pow43(spec.is[i]) as f32 * pow2_quarter(gg) as f32;
            i += 1;
        }
    } else {
        // Long blocks: scalefactor per long sfb.
        for i in 0..NLINES {
            let mut s = 0;
            while s < 21 && (i as u16) >= sfb.long[s + 1] {
                s += 1;
            }
            let sc = spec.scalefac_l[s] + if g.preflag { t::PRETAB[s] as i32 } else { 0 };
            let gain = pow2_quarter(gg) * powf_neg(scale_exp * sc as f64);
            xr[i] = (signed_pow43(spec.is[i]) * gain) as f32;
        }
    }
}

/// 2^(-x): the scalefactor attenuation (each scalefac step is 2^(-scale·sf)).
#[inline]
fn powf_neg(x: f64) -> f64 {
    pow2_quarter(-4.0 * x)
}

#[inline]
pub(crate) fn signed_pow43(is: i32) -> f64 {
    let m = cbrt_no_libm((is.unsigned_abs() as f64).powi_int(4));
    if is < 0 {
        -m
    } else {
        m
    }
}

trait PowiInt {
    fn powi_int(self, n: u32) -> f64;
}
impl PowiInt for f64 {
    #[inline]
    fn powi_int(self, n: u32) -> f64 {
        let mut r = 1.0;
        let mut b = self;
        let mut k = n;
        while k > 0 {
            if k & 1 == 1 {
                r *= b;
            }
            b *= b;
            k >>= 1;
        }
        r
    }
}

// ─── 3. Reordering (short blocks) ───────────────────────────────────────────

/// Reorder short-block coefficients from subband order to scalefactor-band order so
/// the IMDCT sees each window's lines contiguously. Long blocks are a no-op.
pub fn reorder(xr: &mut [f32; NLINES], g: &GranuleChannel, sample_rate: u32) {
    if !(g.window_switching && g.block_type == 2) {
        return;
    }
    let sfb = t::sfb_for_rate(sample_rate);
    let mut out = [0.0f32; NLINES];
    // For mixed blocks the first long region stays in place.
    let start_sfb = if g.mixed_block { 3 } else { 0 };
    let start_line = if g.mixed_block {
        sfb.short[3] as usize * 3
    } else {
        0
    };
    // Copy the untouched long head verbatim.
    for i in 0..start_line.min(NLINES) {
        out[i] = xr[i];
    }
    let mut src = start_line;
    let mut dst = start_line;
    for s in start_sfb..13 {
        let width = (sfb.short[s + 1] - sfb.short[s]) as usize;
        // The 3 windows are interleaved in src as [w0..width][w1..width][w2..width],
        // but in the bitstream short coeffs are stored window-interleaved per line.
        for w in 0..3 {
            for k in 0..width {
                let s_idx = src + w * width + k;
                let d_idx = dst + k * 3 + w;
                if s_idx < NLINES && d_idx < NLINES {
                    out[d_idx] = xr[s_idx];
                }
            }
        }
        src += width * 3;
        dst += width * 3;
        if src >= NLINES {
            break;
        }
    }
    *xr = out;
}

// ─── 4. Stereo (MS + intensity) ─────────────────────────────────────────────

/// Apply MS and/or intensity stereo across the two channels' coefficients in place.
/// `mode_ext` bit1 = MS on, bit0 = intensity on. Intensity-stereo position decode is
/// the deferred sub-stage (it needs the LSF/long-short is_pos tables); when intensity
/// is signalled we apply MS to the non-intensity region and leave the intensity region
/// as decoded (clean), never wrong. MS is fully implemented.
pub fn stereo(left: &mut [f32; NLINES], right: &mut [f32; NLINES], mode_ext: u8) {
    let ms = mode_ext & 0x02 != 0;
    if ms {
        let inv_sqrt2 = core::f32::consts::FRAC_1_SQRT_2;
        for i in 0..NLINES {
            let m = left[i];
            let s = right[i];
            left[i] = (m + s) * inv_sqrt2;
            right[i] = (m - s) * inv_sqrt2;
        }
    }
    // Intensity stereo: position decode deferred (see docstring).
}

// ─── 5. Alias reduction ─────────────────────────────────────────────────────

// ISO alias-reduction butterfly coefficients (8 per subband boundary).
static CS: [f32; 8] = [
    0.857492926,
    0.881741997,
    0.949628649,
    0.983314592,
    0.995517816,
    0.999160558,
    0.999899195,
    0.999993155,
];
static CA: [f32; 8] = [
    -0.514495755,
    -0.471731969,
    -0.313377454,
    -0.181913200,
    -0.094574193,
    -0.040965583,
    -0.014198569,
    -0.003699975,
];

/// Alias reduction: butterflies across the 31 subband boundaries (long blocks only;
/// not applied to pure short blocks). Mixed blocks apply it only to the long region.
pub fn alias_reduce(xr: &mut [f32; NLINES], g: &GranuleChannel) {
    let short = g.window_switching && g.block_type == 2;
    if short && !g.mixed_block {
        return;
    }
    // For mixed blocks, only the first 2 subbands (the long region) are aliased.
    let nbands = if short && g.mixed_block { 1 } else { 31 };
    for sb in 0..nbands {
        let base = sb * 18 + 17;
        for i in 0..8 {
            let lo = base - i; // 17,16,...10 of this subband
            let hi = base + 1 + i; // first 8 of next subband
            if hi >= NLINES {
                break;
            }
            let a = xr[lo];
            let b = xr[hi];
            xr[lo] = a * CS[i] - b * CA[i];
            xr[hi] = b * CS[i] + a * CA[i];
        }
    }
}

// ─── 6. IMDCT + windowing + overlap-add ─────────────────────────────────────

/// IMDCT + windowing + overlap-add for one granule/channel. Consumes `xr[0..576]`
/// (one subband = 18 lines), produces `out[0..576]` time-domain samples (18 per
/// subband) and updates the per-channel overlap memory. Implements the long (36-pt),
/// short (3×12-pt), and start/stop window types, plus the long-block frequency
/// inversion (negate odd time samples of odd subbands).
pub fn imdct(
    xr: &[f32; NLINES],
    g: &GranuleChannel,
    state: &mut ChannelState,
    out: &mut [f32; NLINES],
) {
    let short = g.window_switching && g.block_type == 2;
    for sb in 0..32 {
        let mut sub_in = [0.0f32; 18];
        for k in 0..18 {
            sub_in[k] = xr[sb * 18 + k];
        }
        let mut sub_out = [0.0f32; 36];

        let use_short = short && !(g.mixed_block && sb < 2);
        if use_short {
            // 3 overlapping 12-point IMDCTs.
            for w in 0..3 {
                let mut tmp = [0.0f32; 12];
                for i in 0..12 {
                    let mut acc = 0.0f32;
                    for k in 0..6 {
                        acc += sub_in[w + 3 * k] * IMDCT_SHORT[i][k];
                    }
                    tmp[i] = acc * WIN2[i];
                }
                // Place window w at offset 6*w into the 36-length buffer (overlap).
                for i in 0..12 {
                    sub_out[6 * w + i] += tmp[i];
                }
            }
        } else {
            // 36-point long IMDCT with the window type.
            let win: &[f32; 36] = match g.block_type {
                1 if g.window_switching => &WIN1,
                3 if g.window_switching => &WIN3,
                _ => &WIN0,
            };
            for i in 0..36 {
                let mut acc = 0.0f32;
                for k in 0..18 {
                    acc += sub_in[k] * IMDCT_LONG[i][k];
                }
                sub_out[i] = acc * win[i];
            }
        }

        // Overlap-add: first 18 + previous overlap → output; save second 18.
        for i in 0..18 {
            let mut v = sub_out[i] + state.overlap[sb][i];
            // Frequency inversion: for odd subbands, negate odd-indexed time samples.
            if sb & 1 == 1 && i & 1 == 1 {
                v = -v;
            }
            out[sb * 18 + i] = v;
            state.overlap[sb][i] = sub_out[18 + i];
        }
    }
}

// ─── 7. Polyphase synthesis filterbank ──────────────────────────────────────

use crate::mp3_imdct_tables::{SYNTH_D, SYNTH_N};

/// Polyphase synthesis filterbank (ISO/IEC 11172-3 §2.4.3.2, the matrixed formulation):
/// turns the hybrid-filterbank output `sub[32][18]` (32 subbands × 18 time samples) into
/// the 576 PCM samples of one granule/channel. This is the final stage that makes `.mp3`
/// **audible** — without it the decoder runs the whole DSP path but emits silence.
///
/// Concept promise served (RaeenOS_Concept.md, Media / "it just works" pillar):
///   "RaeenOS ships a media stack that just plays the files people actually have — music,
///    video, photos — out of the box, with no codec hunts and no bundled spyware."
/// MP3 is the dominant consumer audio format; "plays the files people have" is not true
/// until `.mp3` produces sound. This closes that last gap.
///
/// `sub` is the imdct() output in subband-major layout: `sub[sb*18 + ss]` is subband `sb`
/// at time-index `ss`. `pcm_out[32*ss + i]` receives the 32 PCM samples of sub-pass `ss`.
/// The 64×32 cosine matrix N and the 512-tap window D are precomputed `const` tables
/// (no runtime trig, no-libm — the kernel mix path is soft-float). The V[] FIFO in
/// `state` carries across granules and is the only mutable persistent state.
///
/// Untrusted-input discipline: every index is a fixed compile-time bound (no side-info
/// drives any index here), so synthesis cannot OOB; a zeroed `sub` (the upstream
/// corrupt-granule result) yields all-zero PCM, never a panic. Each output sample is
/// finiteness-guarded then hard-clamped to [-1, 1] so a pathological dequant cannot
/// emit NaN/inf PCM.
pub fn synthesis(sub: &[f32; NLINES], state: &mut ChannelState, pcm_out: &mut [f32; NLINES]) {
    let v = &mut state.v_fifo;
    let mut s = [0.0f32; 32];
    let mut u = [0.0f32; 512];
    for ss in 0..18 {
        // 1. Shift the FIFO up by 64.
        v.copy_within(0..960, 64);
        // 2. Gather the 32 subband samples for this sub-pass.
        for k in 0..32 {
            s[k] = sub[k * 18 + ss];
        }
        // 3. Matrix-multiply into the bottom 64 of the FIFO.
        for i in 0..64 {
            let row = &SYNTH_N[i];
            let mut acc = 0.0f32;
            for k in 0..32 {
                acc += row[k] * s[k];
            }
            v[i] = acc;
        }
        // 4. Build the U[512] vector from V (the ISO "build U" gather).
        for i in 0..8 {
            for j in 0..32 {
                u[(i << 6) + j] = v[(i << 7) + j];
                u[(i << 6) + j + 32] = v[(i << 7) + j + 96];
            }
        }
        // 5. Window: U[i] *= D[i].
        for i in 0..512 {
            u[i] *= SYNTH_D[i];
        }
        // 6. Produce 32 PCM samples (the sum over the 16 window slices).
        for i in 0..32 {
            let mut acc = 0.0f32;
            for j in 0..16 {
                acc += u[(j << 5) + i];
            }
            // Belt-and-braces: bound any NaN/inf a pathological dequant could produce,
            // then hard-clamp to the PCM range (D[] already carries the full gain).
            if !acc.is_finite() {
                acc = 0.0;
            }
            pcm_out[32 * ss + i] = acc.clamp(-1.0, 1.0);
        }
    }
}

#[cfg(test)]
mod selftests {
    use super::*;

    #[test]
    fn cbrt_is_accurate() {
        for &x in &[1.0f64, 8.0, 27.0, 1000.0, 2.0, 100.0, 8206.0f64.powi_int(4)] {
            let c = cbrt_no_libm(x);
            // c^3 ≈ x
            let rel = ((c * c * c) - x).abs() / x.max(1.0);
            assert!(rel < 1e-5, "cbrt({}) rel err {}", x, rel);
        }
    }

    #[test]
    fn pow2_quarter_matches_known() {
        // 2^(0/4)=1, 2^(4/4)=2, 2^(8/4)=4, 2^(-4/4)=0.5
        assert!((pow2_quarter(0.0) - 1.0).abs() < 1e-5);
        assert!((pow2_quarter(4.0) - 2.0).abs() < 1e-4);
        assert!((pow2_quarter(8.0) - 4.0).abs() < 1e-4);
        assert!((pow2_quarter(-4.0) - 0.5).abs() < 1e-5);
    }
}
