//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE     int   xyzw
// TEXCOORD                 1   xyzw        1     NONE     int   xyzw
// TEXCOORD                 2   xyzw        2     NONE    uint   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_input_ps constant v0.xyzw
dcl_input_ps constant v1.xyzw
dcl_input_ps constant v2.xyzw
dcl_output o0.xyzw
dcl_temps 3
umin r0.xyzw, v0.xyzw, v2.xyzw
imin r1.xyzw, v0.xyzw, v1.xyzw
imax r2.xyzw, v0.xyzw, v1.xyzw
iadd r1.xyzw, r1.xyzw, r2.xyzw
imad r2.xyzw, v0.xyzw, v1.xyzw, r2.xyzw
iadd r0.xyzw, r0.xyzw, r1.xyzw
umax r1.xyzw, v1.xyzw, v2.xyzw
iadd r0.xyzw, r0.xyzw, r1.xyzw
iadd r0.xyzw, r2.xyzw, r0.xyzw
bfrev r1.xyzw, v2.xyzw
iadd r0.xyzw, r0.xyzw, r1.xyzw
countbits r1.xyzw, v2.xyzw
iadd r0.xyzw, r0.xyzw, r1.xyzw
firstbit_hi r1.xyzw, v2.xyzw
iadd r1.xyzw, -r1.xyzw, l(31, 31, 31, 31)
movc r1.xyzw, v2.xyzw, r1.xyzw, l(-1,-1,-1,-1)
iadd r0.xyzw, r0.xyzw, r1.xyzw
firstbit_lo r1.xyzw, v2.xyzw
iadd r0.xyzw, r0.xyzw, r1.xyzw
firstbit_shi r1.xyzw, v0.xyzw
ieq r2.xyzw, r1.xyzw, l(-1, -1, -1, -1)
iadd r1.xyzw, -r1.xyzw, l(31, 31, 31, 31)
movc r1.xyzw, r2.xyzw, l(-1,-1,-1,-1), r1.xyzw
iadd o0.xyzw, r0.xyzw, r1.xyzw
ret 
// Approximately 25 instruction slots used
